version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PassW0rd
    ports:
      - 27017:27017
      
  django:
    build: ./seed_api_project
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongodb

